/**
 * writes tools/blender/characters/rig.json from src/characters/skeleton.ts so
 * the blender build and the runtime share one skeleton.
 *
 *   npx tsx tools/characters/export-rig.ts
 *
 * besides the joints it records where the knife handle ends up relative to
 * the right hand once the stance is applied, mapped back into the bind pose,
 * so the right glove can be modelled as a fist closed around it.
 * three.js space: y up, the model faces +z with its left side on +x, metres.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Group, Matrix4, Quaternion, Vector3 } from 'three';
import { ALL_JOINTS, bindPose, boneAxisSign, buildSkeleton } from '../../src/characters/skeleton';
import { applyKnifeIdlePose, attachKnifeModel, buildArmRig, loadKnifeMesh } from '../../src/multiplayer/playerRig';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const RIG_JSON = path.join(ROOT, 'tools', 'blender', 'characters', 'rig.json');

const r5 = (v: number) => Math.round(v * 1e5) / 1e5;
const vec = (v: Vector3) => [r5(v.x), r5(v.y), r5(v.z)];

export async function buildRigJson(): Promise<Record<string, unknown>> {
  const bind = bindPose(ALL_JOINTS);
  const children = new Map<string, string[]>();
  for (const j of bind) {
    if (j.parent) children.set(j.parent, [...(children.get(j.parent) ?? []), j.name]);
  }
  const joints = bind.map((j) => {
    const axis = new Vector3(boneAxisSign(j.name), 0, 0).applyQuaternion(j.quaternion).normalize();
    // length to the child along the bone axis, leaves get a short stub
    const kids = children.get(j.name) ?? [];
    const onAxis = kids
      .map((k) => bind.find((b) => b.name === k)!.position.clone().sub(j.position))
      .filter((d) => d.clone().normalize().dot(axis) > 0.99);
    const length = onAxis.length > 0 ? onAxis[0].length() : 0.06;
    return {
      name: j.name,
      parent: j.parent,
      position: vec(j.position),
      quaternion: [r5(j.quaternion.x), r5(j.quaternion.y), r5(j.quaternion.z), r5(j.quaternion.w)],
      axis: vec(axis),
      length: r5(length),
    };
  });

  // pose a skeleton into the knife stance with the real third-person knife
  const posedRoot = new Group();
  const posedBones = buildSkeleton();
  posedRoot.add(posedBones.get('pelvis')!);
  posedRoot.updateMatrixWorld(true);
  const rig = buildArmRig(posedRoot)!;
  attachKnifeModel(rig.rightWeaponHand, await loadKnifeMesh());
  applyKnifeIdlePose(rig, 0);
  posedRoot.updateMatrixWorld(true);

  const knife = posedRoot.getObjectByName('RemoteKnifeModel')!;
  let inner = knife;
  knife.traverse((o) => {
    if (o.name.startsWith('ProceduralKnife:')) inner = o;
  });
  const gripSocket = inner.getObjectByName('socket_grip');
  const gripWorld = gripSocket ? gripSocket.getWorldPosition(new Vector3()) : inner.getWorldPosition(new Vector3());
  const axisWorld = new Vector3(1, 0, 0).applyQuaternion(inner.getWorldQuaternion(new Quaternion())).normalize();

  // posed hand frame -> bind hand frame
  const bindRoot = new Group();
  const bindBones = buildSkeleton();
  bindRoot.add(bindBones.get('pelvis')!);
  bindRoot.updateMatrixWorld(true);
  const toBind = (bone: string) => {
    const posed = posedBones.get(bone)!.matrixWorld;
    const rest = bindBones.get(bone)!.matrixWorld;
    return new Matrix4().copy(rest).multiply(new Matrix4().copy(posed).invert());
  };
  const handToBind = toBind('hand_r');
  const gripBind = gripWorld.clone().applyMatrix4(handToBind);
  const axisBind = axisWorld.clone().transformDirection(handToBind);

  // the same for the left hand's resting spot (no item, just the stance)
  const wristL = posedBones.get('hand_l')!.getWorldPosition(new Vector3());

  return {
    note: 'generated by tools/characters/export-rig.ts from src/characters/skeleton.ts, do not edit',
    space: 'three.js: y up, model faces +z, left side on +x, metres',
    joints,
    knife: {
      bone: 'hand_r',
      // handle centre and blade direction in the bind pose (glove space)
      handleCenter: vec(gripBind),
      handleAxis: vec(axisBind),
      handleLength: 0.12,
      handleRadius: 0.0125,
    },
    stance: {
      // posed wrist height, only for sanity checks
      wristL: vec(wristL),
    },
  };
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const json = await buildRigJson();
  writeFileSync(RIG_JSON, `${JSON.stringify(json, null, 1)}\n`);
  console.log(`[export-rig] wrote ${path.relative(ROOT, RIG_JSON)} (${(json.joints as unknown[]).length} joints)`);
}
