/**
 * derives the server side run rules for every timed map from its meta.json and
 * writes them as a supabase migration (upserts into webstrafe_map_rules).
 *
 *   npx tsx tools/surf/mapRules.ts          # rewrite the seed migration
 *   npx tsx tools/surf/mapRules.ts --check  # exit 1 if it is out of date
 *
 * minimum times: the shortest straight line through the zones in order at
 * MAX_PLAUSIBLE_SPEED (no one surfs faster than that, bhop maps use a lower cap), and for the whole run
 * also PAR_FLOOR of the map's par time when it has one.
 */
import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MAX_PLAUSIBLE_SPEED = 90;
/** bhop tops out far lower than surf, no ramps to pump speed from */
export const MAX_PLAUSIBLE_BHOP_SPEED = 35;
export const PAR_FLOOR = 0.45;

type Vec3 = [number, number, number];

interface Trigger {
  id: string;
  type: 'start' | 'checkpoint' | 'finish' | 'teleport';
  min: Vec3;
  max: Vec3;
  stage?: number;
}

interface Meta {
  id: string;
  triggers?: Trigger[];
  modes?: string[];
  parTimeMs?: number;
}

export interface MapRule {
  mapId: string;
  modes: string[];
  stages: number[];
  minTimeMs: number;
  minStageMs: number[];
}

function boxDistance(a: Trigger, b: Trigger): number {
  let sum = 0;
  for (let i = 0; i < 3; i += 1) {
    const gap = Math.max(0, a.min[i] - b.max[i], b.min[i] - a.max[i]);
    sum += gap * gap;
  }
  return Math.sqrt(sum);
}

export function ruleForMeta(meta: Meta): MapRule | null {
  const triggers = meta.triggers ?? [];
  const start = triggers.find((t) => t.type === 'start');
  const finish = triggers.find((t) => t.type === 'finish');
  if (!start || !finish) return null;
  // one volume per stage label, lowest first, like the client's RunTimer
  const byStage = new Map<number, Trigger>();
  for (const t of triggers) {
    if (t.type === 'checkpoint' && typeof t.stage === 'number' && !byStage.has(t.stage)) byStage.set(t.stage, t);
  }
  const stages = [...byStage.keys()].sort((a, b) => a - b);
  const path = [start, ...stages.map((s) => byStage.get(s)!), finish];
  const topSpeed = meta.id.startsWith('bhop_') ? MAX_PLAUSIBLE_BHOP_SPEED : MAX_PLAUSIBLE_SPEED;
  const minStageMs: number[] = [];
  for (let i = 1; i < path.length; i += 1) {
    minStageMs.push(Math.floor((boxDistance(path[i - 1], path[i]) / topSpeed) * 1000));
  }
  const geometric = minStageMs.reduce((a, b) => a + b, 0);
  const par = typeof meta.parTimeMs === 'number' && meta.parTimeMs > 0 ? Math.floor(meta.parTimeMs * PAR_FLOOR) : 0;
  return {
    mapId: meta.id,
    modes: meta.modes?.length ? meta.modes : ['surf'],
    stages,
    minTimeMs: Math.max(1000, geometric, par),
    minStageMs,
  };
}

const root = resolve(fileURLToPath(new URL('../..', import.meta.url)));
export const RULES_MIGRATION = join(root, 'supabase/migrations/20260927000002_map_rules.sql');

export function collectRules(): MapRule[] {
  const mapsDir = join(root, 'public/maps');
  const rules: MapRule[] = [];
  for (const id of readdirSync(mapsDir).sort()) {
    const metaPath = join(mapsDir, id, 'meta.json');
    if (!existsSync(metaPath)) continue;
    const rule = ruleForMeta(JSON.parse(readFileSync(metaPath, 'utf8')) as Meta);
    if (rule) rules.push(rule);
  }
  return rules;
}

const sqlText = (v: string) => `'${v.replace(/'/g, "''")}'`;
const sqlArray = (v: Array<string | number>, type: string) =>
  `'{${v.map((x) => (typeof x === 'string' ? `"${x}"` : String(x))).join(',')}}'::${type}[]`;

export function renderMigration(rules: MapRule[]): string {
  const rows = rules.map((r) =>
    `  (${sqlText(r.mapId)}, ${sqlArray(r.modes, 'text')}, ${sqlArray(r.stages, 'integer')}, ${r.minTimeMs}, ${sqlArray(r.minStageMs, 'integer')})`,
  );
  return `-- generated by tools/surf/mapRules.ts from public/maps/*/meta.json, do not edit by hand.
-- run after 20260927000001_surf_runs_and_kills.sql. re-run whenever a map's zones change.
insert into public.webstrafe_map_rules (map_id, modes, stages, min_time_ms, min_stage_ms)
values
${rows.join(',\n')}
on conflict (map_id) do update set
  modes = excluded.modes,
  stages = excluded.stages,
  min_time_ms = excluded.min_time_ms,
  min_stage_ms = excluded.min_stage_ms,
  updated_at = now();
`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const text = renderMigration(collectRules());
  if (process.argv.includes('--check')) {
    const current = existsSync(RULES_MIGRATION) ? readFileSync(RULES_MIGRATION, 'utf8') : '';
    if (current !== text) {
      console.error('map rules migration is out of date, run: npx tsx tools/surf/mapRules.ts');
      process.exit(1);
    }
    console.log('map rules migration is up to date');
  } else {
    writeFileSync(RULES_MIGRATION, text);
    console.log(`wrote ${RULES_MIGRATION}`);
  }
}
